name: Build CPP

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Program
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make makefile
